# Generated by Django 6.0.2 on 2026-02-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='料理名')),
                ('tool', models.CharField(max_length=50, verbose_name='調理器具（レンジ・炊飯器など）')),
                ('ingredients', models.TextField(verbose_name='材料')),
                ('instructions', models.TextField(verbose_name='作り方（3ステップ！）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
        ),
    ]
