# Generated by Django 6.0.2 on 2026-02-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='poster',
            field=models.CharField(default='りえ', max_length=50, verbose_name='投稿者'),
        ),
    ]
