# Generated by Django 6.0.2 on 2026-02-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('メイン', 'メインのおかず'), ('副菜', '副菜・おつまみ'), ('ご飯・麺', 'ご飯・麺類'), ('スープ', 'スープ・汁物')], default='メイン', max_length=50, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '★☆☆（レンジ等で超簡単！）'), (2, '★★☆（ふつう）'), (3, '★★★（ちょっと頑張る）')], default=1, verbose_name='難易度'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='poster',
            field=models.CharField(default='Rie', max_length=50, verbose_name='投稿者'),
        ),
    ]
