# Generated by Django 6.0.2 on 2026-02-28 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_category_recipe_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆（レンジで3ステップ以内！）'), (2, '★★☆☆☆（レンジor炊飯器で放置！）'), (3, '★★★☆☆（ちょっとステップ多め）'), (4, '★★★★☆（フライパン使ってみよう）'), (5, '★★★★★（気合の本格派！）')], default=1, verbose_name='難易度'),
        ),
        migrations.CreateModel(
            name='CookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cook_logs/', verbose_name='完成写真')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='パパの味付けメモ（次回への改善点など）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作った日')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cook_logs', to='recipes.recipe', verbose_name='作ったレシピ')),
            ],
        ),
    ]
