# Generated by Django 6.0.2 on 2026-02-28 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_difficulty_cooklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=50, verbose_name='お名前')),
                ('text', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('cook_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.cooklog', verbose_name='対象の記録')),
            ],
        ),
    ]
