# Generated by Django 5.1.3 on 2026-03-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="poster",
        ),
        migrations.AddField(
            model_name="recipe",
            name="author",
            field=models.CharField(
                default="りえ", max_length=50, verbose_name="投稿者"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cooklog",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cooklog",
            name="memo",
            field=models.TextField(
                blank=True, null=True, verbose_name="味付けメモ（アレンジ内容など）"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("メイン", "メインのおかず"),
                    ("副菜", "副菜・おつまみ"),
                    ("ご飯・麺", "ご飯・麺類"),
                    ("スープ", "スープ・汁物"),
                    ("sweets", "スイーツ"),
                ],
                default="メイン",
                max_length=50,
                verbose_name="カテゴリ",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
