# Generated by Django 6.0.2 on 2026-03-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipe_poster_recipe_author_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='購入日')),
                ('item_name', models.CharField(max_length=100, verbose_name='品目')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('category', models.CharField(choices=[('food', '食費（自炊）'), ('dining', '外食費'), ('daily', '日用品'), ('beauty', '美容・健康'), ('transport', '交通費'), ('education', '自己研鑽・趣味'), ('utilities', '固定費（光熱費・通信費）'), ('other', 'その他')], default='food', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='食材名')),
                ('quantity', models.CharField(help_text='例: 2個、1/2個など', max_length=50, verbose_name='数量')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='賞味期限')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cooklog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
