# Generated by Django 6.0.2 on 2026-03-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_budget_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('food', '食費（自炊）'), ('dining', '外食費'), ('daily', '日用品'), ('beauty', '美容・健康'), ('transport', '交通費'), ('education', '自己研鑽・趣味'), ('utilities', '固定費（光熱費・通信費）'), ('other', 'その他')], default='food', max_length=20, verbose_name='カテゴリー'),
        ),
    ]
