# Generated by Django 6.0.2 on 2026-03-25 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_cooklog_user_inventory_user_recipe_author_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', '食費（自炊）'), ('dining', '外食費'), ('daily', '日用品'), ('beauty', '美容・健康'), ('transport', '交通費'), ('education', '自己研鑽・趣味'), ('utilities', '固定費（光熱費・通信費）'), ('other', 'その他')], max_length=20, verbose_name='カテゴリー')),
                ('amount', models.IntegerField(default=0, verbose_name='予算額')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
