# Generated by Django 6.0.2 on 2026-03-25 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_categorybudget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': '在庫管理'},
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='expiry_date',
            new_name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='added_at',
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(default='個', max_length=20, verbose_name='単位'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='食材名'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
