# Generated by Django 6.0.2 on 2026-03-25 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='購入日'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
    ]
